SCREEN_WIDTH = 1280

SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20 #radius of the player's ship

LINE_WIDTH = 2 # the width of the lines that draw the player's ship

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20

ASTEROID_KINDS = 3

ASTEROID_SPAWN_RATE_SECONDS = 0.8

# Difficulty scaling
ASTEROID_DIFFICULTY_RAMP_SECONDS = 30.0
ASTEROID_MAX_DIFFICULTY_MULTIPLIER = 3.0

# Asteroid splitting speed multiplier bounds
ASTEROID_SPLIT_SPEED_MIN = 1.1
ASTEROID_SPLIT_SPEED_MAX = 1.4

ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5 

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Gameplay constants
PLAYER_LIVES = 3
PLAYER_INVINCIBILITY_SECONDS = 2.0
SHOT_LIFETIME_SECONDS = 2.0

# Scoring
SCORE_SMALL_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_LARGE_ASTEROID = 20
