# Screen dimensions
SCREEN_WIDTH = 1280

SCREEN_HEIGHT = 720

# Player ship sizing and movement
PLAYER_RADIUS = 20  # radius of the player's ship

LINE_WIDTH = 2  # the width of the lines that draw the player's ship

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

# Base asteroid sizing and spawn cadence
ASTEROID_MIN_RADIUS = 20

ASTEROID_KINDS = 3

ASTEROID_SPAWN_RATE_SECONDS = 0.8

# Difficulty scaling
ASTEROID_DIFFICULTY_RAMP_SECONDS = 30.0
ASTEROID_MAX_DIFFICULTY_MULTIPLIER = 3.0

# Asteroid splitting speed multiplier bounds
ASTEROID_SPLIT_SPEED_MIN = 1.1
ASTEROID_SPLIT_SPEED_MAX = 1.4

ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Asteroid field tuning (spawn movement + difficulty ramp)
ASTEROID_SPEED_MIN = 40
ASTEROID_SPEED_MAX = 100
ASTEROID_ROTATION_MIN = -30
ASTEROID_ROTATION_MAX = 30
# Child asteroid speed multiplier when splitting
ASTEROID_SPLIT_SPEED_MIN = 1.05
ASTEROID_SPLIT_SPEED_MAX = 1.35
# Difficulty increases over time to add pressure
ASTEROID_DIFFICULTY_RAMP_SECONDS = 20.0
ASTEROID_MAX_DIFFICULTY_MULTIPLIER = 2.0

# Shot configuration
SHOT_RADIUS = 5 

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Gameplay constants (survivability)
PLAYER_LIVES = 3
PLAYER_INVINCIBILITY_SECONDS = 2.0
SHOT_LIFETIME_SECONDS = 2.0

# Visual effects
PLAYER_TRAIL_LENGTH = 10
SHOT_TRAIL_LENGTH = 12
TRAIL_MAX_ALPHA = 140
GLOW_ALPHA = 160
BLUR_SCALE = 0.6
PARTICLE_BURST_COUNT = 28
PARTICLE_BURST_SPEED_RANGE = (80, 220)
PARTICLE_BURST_LIFE_RANGE = (0.4, 1.0)
PARTICLE_BURST_SIZE_RANGE = (2, 5)
PARTICLE_BURST_COLOR = (255, 200, 120)
PARTICLE_BURST_ALPHA = 200
EXPLOSION_FRAME_SIZE = 64
EXPLOSION_COLUMNS = 4
EXPLOSION_ROWS = 4
EXPLOSION_FRAME_TIME = 0.04

# Scoring
SCORE_SMALL_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_LARGE_ASTEROID = 20
